version: "3.8"

services:
  dashboard:
    container_name: dashboard_container
    build: ./dashboard
    restart: always
    command: npm run dev
    volumes:
      - ./dashboard/public:/code/public
      - ./dashboard/src:/code/src
    ports:
      - 8000:8000
    depends_on:
      - backend

  backend:
    container_name: backend_container
    build: ./backend
    restart: always
    command: python run.py
    volumes:
      - ./backend:/code
    ports:
      - 5000:5000
